### ISSUE TITLE
On rerendering a react element and updated props

### ISSUE THREAD

**Issue by phaistonian** [thejameskyle/babel-react-optimize#14]
Say you have something like this:

![image](https://cloud.githubusercontent.com/assets/796530/15010973/e7bf7d80-11f7-11e6-81eb-9bc601da624b.png)

the `data` map is updated and yet, when rerendring the element does not respect the changes because, as It turnt out, the react element is "evaluated" once and referenced on each run.

The solution was to use a factory function, i.e `getData` that's assigned to the prop instead of directly using `data`.

ps: I am sure I am not making much sense here.

**Comment by phaistonian** [comment]
Apparently this is "caused" by the [react-constant-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements) transform.

Is there a way to disable this explicitly disable this plugin (and keep the rest of the preset) or should I install each plugin separately?

**Comment by thejameskyle** [comment]
Yeah that plugin doesn't live in this repo, open an issue in https://phabricator.babeljs.io. I don't know what can/should be done though since you're doing something unsafe.

My recommendation would be to manually specify plugins.
