### ISSUE TITLE
Issues with IE 10 and 11

### ISSUE THREAD

**Issue by gschwa** [thejameskyle/babel-react-optimize#16]
When using this preset, I am getting the following error only in IE 10 and IE 11:

```
ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React.
```

**Comment by thejameskyle** [comment]
I need you to give me more information than that. Can you create a reproduction case?

**Comment by gschwa** [comment]
Sorry @thejameskyle that was a pretty horrible bug report. Here are some steps to reproduce:

1. Pull down: https://github.com/gschwa/react-redux-starter-kit which is a fork of a very popular react-redux-starter-kit
2. npm install (requires npm 3.x)
3. npm deploy:prod (creates a `dist` directory with the babel compiled code)
4. npm install http-server -g
5. http-server ./dist
6. Open in either IE 10 or IE 11 to see the error (all other modern browsers work) You can DL a IE 11 VM  from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/

The preset is configured here: https://github.com/gschwa/react-redux-starter-kit/blob/master/build/webpack.config.js#L131

In order, to see it in a non-minified version I did the following:

1. Changed `production` to `development` here: https://github.com/gschwa/react-redux-starter-kit/blob/master/build/webpack.config.js#L130
2. npm run deploy:dev
3. http-server ./dist (stop the one from before first or you will get an address conflict)
4. Open in IE 11 or IE 10

**Comment by creatorkuang** [comment]
This issue is also happen in Android browser(test with Galaxy Note 3), But Chrome Mobile is OK.

**Comment by creatorkuang** [comment]
@gschwa it's not because of react-optimize, you could check this:  https://github.com/creatorkuang/react-redux-starter-kit/commit/dcb1c88c03d65b79c8ec70d63d2ef3e2236ffa84 
to see if it help.

**Comment by gschwa** [comment]
@creatorkuang Thank you that worked.

**Comment by oliviertassinari** [comment]
The root of this issue seems to be `transform-react-inline-elements` that require a global `Symbol` polyfill.
Have a look at https://babeljs.io/docs/plugins/transform-react-inline-elements/ for more details.

**Comment by masylum** [comment]
I'm also getting this issue in IE11. I'm loading `babel-polyfill`with webpack but I'm not sure if I'm doing something wrong or not. I'm currently doing this:

```js
  entry: {
    app: [
      'babel-polyfill',
      './src/index'
    ]
}

```

This should be enough to have `transform-react-inline-elements` working, no?

**Comment by DimitryDushkin** [comment]
Actually no sense to load all 'babel-polyfill' (it's ~60Kb minified), you can just include Symbol polyfill in webpack config entries:
```
  entry: {
    app: [
      'core-js/es6/symbol',
      './src/index'
    ]
}
```
or import in your index.jsx (entry point for browser app):
```
import 'core-js/es6/symbol.js';
```
