### ISSUE TITLE
Benchmark of pure class to function?

### ISSUE THREAD

**Issue by oliviertassinari** [thejameskyle/babel-react-optimize#3]
Is [`pure-class-to-function`](https://github.com/thejameskyle/babel-react-optimize/tree/master/packages/babel-plugin-transform-react-pure-class-to-function) really more optimized for production?
The advantage isn't obvious. As far as I know, React hasn't yet introduced specific optimization for stateless functional component. So I'm wondering if the advantage is regarding the build size or the runtime.
Do you have some benchmark?

**Comment by thejameskyle** [comment]
Its mostly about the compiled output right now with the promise of better performance in the future.
